[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.31"
evm_version = "osaka"
optimizer = true
optimizer_runs = 10000
via_ir = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@pythnetwork/entropy-sdk-solidity/=lib/pyth-crosschain/target_chains/ethereum/entropy_sdk/solidity/",
    "forge-std/=lib/forge-std/src/",
]

[etherscan]
monad = { key = "5W8T6XFNJ2V6KVA6IFXDIRDCS1GNS665AD", url = "https://api.monadscan.com/api", chain = 143 }
